[package]
name = "bakuryu"
version = "1.0.0"
edition = "2024"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
diesel = { version = "2.2.0", features = ["postgres", "r2d2"] }
dotenvy = "0.15"
actix-web-httpauth = "0.8.2"
actix-multipart = "0.7.2"
os_info = "3"
rustc_version_runtime = "0.3.0"
jsonwebtoken = { version = "10.3.0", features = ["aws_lc_rs"] }
env_logger = "0.11.9"
fern = "0.6"
chrono = { version = "0.4", features = ["serde"] }
log = "0.4"
